version: '3'
services: 
    people-app:
        build: .docker/development
        ports: 
            - 4000:4000
        depends_on: 
            - people-db
        volumes:
            - .:/opt/people_app
    people-db:
        image: postgres:10
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: people_dev
            POSTGRES_PASSWORD: dp
        volumes:
            - people-db-vol:/var/lib/postgresql/data
volumes:
    people-db-vol: ~
